version: "1.5"    # optional

services:
  frontend:
    # container_name: frontend # (default:key)
    image: "docker-compose-frontend" # image_name
    build: ./frontend # Dockerize edilecek klasör (dockerfile)
    ports:
    # dış/iç port numaraları
      - 5173:5173
      - 3000:5173
      - 80:5173         # browsera sadece localhost yazinca bu calisir
    restart: on-failure # hata anında tekrar çalıştır.
    depends_on:
      - backend

  backend:
    # container_name: backend
    image: "docker-compose-backend"      #image name
    build: ./backend
    ports: 
      - 8000:8000     # dis ic port numaralari
    restart: on-failure       #hata olursa tekrar calistir
    volumes:
      # fiziksel yollar (external:internal)
      - $PWD/backend/logs:/backend/logs
      - $PWD/backend/upload:/backend/upload            #Bu kismi yazdik ki container silindiginde veriler ve loglar silinmesin

      #docker compose terminalde cok sayida islem yapmaktan kurtariyor

  
