# Altyapi
FROM node:alpine3.18

# Calisma Alani
WORKDIR /app

# Dosyalari Aktar
# COPY hello.js /app/
# Bunu tüm dosyalar icin yapmak icin
COPY . .

# Image'i container'a dönüstürmek icin
CMD node hello.js





